### ISSUE TITLE
Update for modern MonadTransControl C.hs for System.Posix.ACL.C

### ISSUE THREAD

**Issue by ghost** [tensor5/posix-acl#1]
I have a working source with the needed modifications to support the type family in MonadTransControl 1.x.
If you want I can send the changes. Using current stack lts will not play nicely with posix-acl 2.x.

**Comment by tensor5** [comment]
Thanks, I will update it myself soon, just needed a motivation.

**Comment by ghost** [comment]
Very nice. I look forward to a working upstream!

**Comment by ghost** [comment]
Looks good. Worked well in my program. Thanks for the fix!

Any chance posix-acl will make its way into stack?

**Comment by tensor5** [comment]
> Any chance posix-acl will make its way into stack?

If you need it, open an issue so that I don't forget.
